In [1]:
# Np.min
# Np.argmin
# Np.max
# Np.argmax
# Np.sqrt
# Np.sin
# Np.cos
# Np.cumsum
# Cumulative sum
# Previous elements + next elements
# For loop
# While loop
# Np.nditer
# Np.ndenumerate

In [2]:
import numpy as np

In [4]:
a = np.random.randint(1,100,10)
a

array([16, 88, 92, 43, 18, 29, 36,  3, 59, 30])

In [5]:
np.max(a)

92

In [6]:
max(a)

92

In [7]:
min(a)

3

In [8]:
np.min(a)

3

In [9]:
np.max(a)

92

In [10]:
np.argmax(a)

2

In [11]:
np.min(a)

3

In [12]:
np.argmin(a)

7

In [14]:
# slicing and indexing

In [15]:
a

array([16, 88, 92, 43, 18, 29, 36,  3, 59, 30])

In [17]:
np.prod(a)

-1581670400

In [18]:
np.product(a)

-1581670400

In [20]:
total = 1
for i in a:
    total*=i
print(total)

-1581670400


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19808\612670709.py:3: RuntimeWarning: overflow encountered in scalar multiply
  total*=i


In [22]:
a = np.random.randint(1,100,4)

a

array([29, 78, 67, 14])

In [24]:
np.prod(a)

2121756

In [25]:
np.prod(a)

2121756

In [28]:
eval('16, 88, 92, 43, 18, 29, 36,  3, 59, 30'.replace(',','*'))

555810136104960

In [32]:
a = np.random.randint(1,100,(5,5))
a

array([[32, 38, 19, 77, 75],
       [87, 43, 17, 91, 83],
       [37,  7, 13, 25,  7],
       [92, 30, 69, 83, 70],
       [51, 40, 24, 54, 91]])

In [35]:
np.min(a,axis=1)

array([19, 17,  7, 30, 24])

In [36]:
np.min(a,axis=0)

array([32,  7, 13, 25,  7])

In [ ]:
# 32,7,13,25,7

In [37]:
np.max(a)

92

In [38]:
a

array([[32, 38, 19, 77, 75],
       [87, 43, 17, 91, 83],
       [37,  7, 13, 25,  7],
       [92, 30, 69, 83, 70],
       [51, 40, 24, 54, 91]])

In [39]:
np.max(a,axis=1)

array([77, 91, 37, 92, 91])

In [40]:
np.argmax(a,axis=1)

array([3, 3, 0, 0, 4], dtype=int64)

In [41]:
np.min(a,axis=1)

array([19, 17,  7, 30, 24])

In [42]:
a

array([[32, 38, 19, 77, 75],
       [87, 43, 17, 91, 83],
       [37,  7, 13, 25,  7],
       [92, 30, 69, 83, 70],
       [51, 40, 24, 54, 91]])

In [44]:
np.argmin(a,axis=1)

array([2, 2, 1, 1, 2], dtype=int64)

In [45]:
a

array([[32, 38, 19, 77, 75],
       [87, 43, 17, 91, 83],
       [37,  7, 13, 25,  7],
       [92, 30, 69, 83, 70],
       [51, 40, 24, 54, 91]])

In [46]:
np.sum(a)

1255

In [47]:
np.sum(a,axis=1)

array([241, 321,  89, 344, 260])

In [48]:
32+38+19+77+75

241

In [49]:
np.sum(a,axis=0)

array([299, 158, 142, 330, 326])

In [50]:
a

array([[32, 38, 19, 77, 75],
       [87, 43, 17, 91, 83],
       [37,  7, 13, 25,  7],
       [92, 30, 69, 83, 70],
       [51, 40, 24, 54, 91]])

In [ ]:
4*4 = 16
4

In [51]:
np.sqrt(a)

array([[5.65685425, 6.164414  , 4.35889894, 8.77496439, 8.66025404],
       [9.32737905, 6.55743852, 4.12310563, 9.53939201, 9.11043358],
       [6.08276253, 2.64575131, 3.60555128, 5.        , 2.64575131],
       [9.59166305, 5.47722558, 8.30662386, 9.11043358, 8.36660027],
       [7.14142843, 6.32455532, 4.89897949, 7.34846923, 9.53939201]])

In [52]:
5.65685425*5.65685425

32.00000000574307

In [54]:
a*a

array([[1024, 1444,  361, 5929, 5625],
       [7569, 1849,  289, 8281, 6889],
       [1369,   49,  169,  625,   49],
       [8464,  900, 4761, 6889, 4900],
       [2601, 1600,  576, 2916, 8281]])

In [55]:
a**2

array([[1024, 1444,  361, 5929, 5625],
       [7569, 1849,  289, 8281, 6889],
       [1369,   49,  169,  625,   49],
       [8464,  900, 4761, 6889, 4900],
       [2601, 1600,  576, 2916, 8281]])

In [57]:
np.sqrt(a**2).astype(int)

array([[32, 38, 19, 77, 75],
       [87, 43, 17, 91, 83],
       [37,  7, 13, 25,  7],
       [92, 30, 69, 83, 70],
       [51, 40, 24, 54, 91]])

In [58]:
# Previous elements + next elements
# For loop
# While loop
# Np.nditer
# Np.ndenumerate

In [59]:
a = np.array([1,2,3,5,67])

# 1,2,34,5,6

# 1
# 3
# 37
# 42
# 48


np.cumsum(a)

array([ 1,  3,  6, 11, 78])

In [60]:
np.cumprod(a)

array([   1,    2,    6,   30, 2010])

In [62]:
a = np.array([1,3,4,6,8])

for i in a:
    print(i)

1
3
4
6
8


In [63]:
a = np.random.randint(1,100,(5,5))
a

array([[ 4,  8, 45, 37, 90],
       [42, 40, 81, 77, 21],
       [56, 46, 55, 78,  2],
       [81,  4, 67,  5, 52],
       [18, 86, 25, 98,  6]])

In [64]:
for i in a:
    print(i)

[ 4  8 45 37 90]
[42 40 81 77 21]
[56 46 55 78  2]
[81  4 67  5 52]
[18 86 25 98  6]


In [65]:
for i in a.flatten():
    print(i)

4
8
45
37
90
42
40
81
77
21
56
46
55
78
2
81
4
67
5
52
18
86
25
98
6


In [66]:
for i in np.nditer(a):
    print(i)

4
8
45
37
90
42
40
81
77
21
56
46
55
78
2
81
4
67
5
52
18
86
25
98
6


In [67]:
a = np.random.randint(1,1001,(3,4,5,6,7,8))

In [69]:
a.ndim

6

In [75]:
# for i in a.flatten():
#     print(i)

In [76]:
# for i in np.nditer(a):
#     print(i)

In [80]:
a = np.array([12,34,432,345,567,8])


for index,value in enumerate(a):
    print(index,value)

0 12
1 34
2 432
3 345
4 567
5 8


In [83]:
a = np.array([12,34,432,345,567,8])

for index,value in np.ndenumerate(a):
    print(index,value)

(0,) 12
(1,) 34
(2,) 432
(3,) 345
(4,) 567
(5,) 8


In [85]:
a = np.random.randint(1,100,(3,3,3))

a

array([[[62,  6, 33],
        [86,  2, 83],
        [ 7, 14, 68]],

       [[46, 18, 69],
        [70, 88, 96],
        [52, 17, 59]],

       [[87, 23, 15],
        [86, 36, 71],
        [84, 39, 87]]])

In [87]:
for index,value in np.ndenumerate(a):
    print(index,value)

(0, 0, 0) 62
(0, 0, 1) 6
(0, 0, 2) 33
(0, 1, 0) 86
(0, 1, 1) 2
(0, 1, 2) 83
(0, 2, 0) 7
(0, 2, 1) 14
(0, 2, 2) 68
(1, 0, 0) 46
(1, 0, 1) 18
(1, 0, 2) 69
(1, 1, 0) 70
(1, 1, 1) 88
(1, 1, 2) 96
(1, 2, 0) 52
(1, 2, 1) 17
(1, 2, 2) 59
(2, 0, 0) 87
(2, 0, 1) 23
(2, 0, 2) 15
(2, 1, 0) 86
(2, 1, 1) 36
(2, 1, 2) 71
(2, 2, 0) 84
(2, 2, 1) 39
(2, 2, 2) 87


In [88]:
a[2][1][2]

71

In [90]:
a[2][1][2] = 98654

In [91]:
a

array([[[   62,     6,    33],
        [   86,     2,    83],
        [    7,    14,    68]],

       [[   46,    18,    69],
        [   70,    88,    96],
        [   52,    17,    59]],

       [[   87,    23,    15],
        [   86,    36, 98654],
        [   84,    39,    87]]])

In [93]:
a[1][2][0] = 420

In [94]:
a

array([[[   62,     6,    33],
        [   86,     2,    83],
        [    7,    14,    68]],

       [[   46,    18,    69],
        [   70,    88,    96],
        [  420,    17,    59]],

       [[   87,    23,    15],
        [   86,    36, 98654],
        [   84,    39,    87]]])

In [98]:
a[-1][-1][0] = 98654

In [99]:
a

array([[[   62,     6,    33],
        [   86,     2,    83],
        [    7,    14,    68]],

       [[   46,    18,    69],
        [   70,    88,    96],
        [  420,    17,    59]],

       [[   87,    23,    15],
        [   86,    36, 98654],
        [98654,    39,    87]]])

In [100]:
a = np.random.randint(1,100,(3,3))
a

array([[85, 85, 31],
       [45, 32, 66],
       [19, 89, 85]])

In [104]:
a[1][-1] = 764

In [105]:
a

array([[ 85,  85,  31],
       [ 45,  32, 764],
       [ 19,  89,  85]])

In [107]:
a = np.random.randint(1,101,(4,4,4,4))
a

array([[[[ 69,  93,  26,  19],
         [ 97,  39,  69,  83],
         [ 31,  97,  20,  84],
         [ 14,  74,   9,  90]],

        [[ 78,  87,  99,  36],
         [ 70,  24,  80,  49],
         [ 86,  89,  86,  87],
         [ 31,  53,  94,  13]],

        [[ 45,  71,   5,  39],
         [ 87,  97,  32,  38],
         [ 41,   5,  26,  25],
         [ 38,  22,  28,   8]],

        [[ 88,  24,  21,  72],
         [ 54,  64,  36,  66],
         [  8,  62,  10,  15],
         [ 73,  49,  34,  13]]],


       [[[ 96,  82,   1,  29],
         [ 51,  23,  42,  81],
         [  2,  22,  67,  20],
         [ 33,  22,  93,  29]],

        [[ 25,  66,  49,  69],
         [ 42,  69,  25,  80],
         [ 73,  30,  43,  84],
         [ 30,  73,  55,  29]],

        [[ 68,  18,  75,  52],
         [ 61,  16,  32,  17],
         [ 65,  78,  16,  49],
         [ 35,  57,  15,  87]],

        [[ 41,  35,  50,  47],
         [ 77,  39, 100,  49],
         [ 54,  67,  30,  59],
         [ 11,  40,  54

In [111]:
a[1][1][2][2] = 567654

In [112]:
a

array([[[[    69,     93,     26,     19],
         [    97,     39,     69,     83],
         [    31,     97,     20,     84],
         [    14,     74,      9,     90]],

        [[    78,     87,     99,     36],
         [    70,     24,     80,     49],
         [    86,     89,     86,     87],
         [    31,     53,     94,     13]],

        [[    45,     71,      5,     39],
         [    87,     97,     32,     38],
         [    41,      5,     26,     25],
         [    38,     22,     28,      8]],

        [[    88,     24,     21,     72],
         [    54,     64,     36,     66],
         [     8,     62,     10,     15],
         [    73,     49,     34,     13]]],


       [[[    96,     82,      1,     29],
         [    51,     23,     42,     81],
         [     2,     22,     67,     20],
         [    33,     22,     93,     29]],

        [[    25,     66,     49,     69],
         [    42,     69,     25,     80],
         [    73,     30, 567654,     84],

In [113]:
# indexing v2.0


a = np.random.randint(1,100,(3,3))
a

array([[55, 38, 94],
       [12, 38,  3],
       [84, 95, 68]])

In [114]:
a[1][0]

12

In [116]:
a[1,0] = 123456

In [117]:
a

array([[    55,     38,     94],
       [123456,     38,      3],
       [    84,     95,     68]])

In [118]:
a[2,2]

68

In [119]:
a[-1,-1]

68

In [120]:
a = np.random.randint(1,1001,(3,3,3))
a

array([[[885, 382,   3],
        [425, 612, 902],
        [980, 714, 304]],

       [[676, 857, 989],
        [ 25, 354, 205],
        [391, 444, 137]],

       [[947, 847, 870],
        [660, 772, 460],
        [772, 576,  94]]])

In [121]:
a[1,,]

array([[676, 857, 989],
       [ 25, 354, 205],
       [391, 444, 137]])

In [122]:
# 2d= [row,col]
# 3d = [arr,row,col]
# 4d = [arr,arr,row,col]
# 5d = [arr,arr,arr,row,col] 

In [124]:
a

array([[[885, 382,   3],
        [425, 612, 902],
        [980, 714, 304]],

       [[676, 857, 989],
        [ 25, 354, 205],
        [391, 444, 137]],

       [[947, 847, 870],
        [660, 772, 460],
        [772, 576,  94]]])

In [127]:
a[1,1,1] = 876543

In [128]:
a

array([[[   885,    382,      3],
        [   425,    612,    902],
        [   980,    714,    304]],

       [[   676,    857,    989],
        [    25, 876543,    205],
        [   391,    444,    137]],

       [[   947,    847,    870],
        [   660,    772,    460],
        [   772,    576,     94]]])

In [129]:
a[2,1,0]

660

In [130]:
a[1,0,2]

989

In [131]:
a[2,2,1]

576

In [132]:
a[2,0,0]

947

In [133]:
a[0,1,2]

902

In [134]:
# slicing

In [135]:
a = np.random.randint(1,100,10)
a

array([35, 15,  2, 11, 18, 63, 85, 45, 63,  1])

In [136]:
a[2:7]

array([ 2, 11, 18, 63, 85])

In [137]:
# 2d

a = np.random.randint(1,100,(3,3))
a

array([[68, 60, 55],
       [51, 72, 21],
       [70, 84, 71]])

In [138]:
# a[r_slicing,c_slicing]

In [139]:
# 51 72
# 70 84

a[1:,0:2]

array([[51, 72],
       [70, 84]])

In [142]:
a[1:,:]

array([[51, 72, 21],
       [70, 84, 71]])

In [143]:
a

array([[68, 60, 55],
       [51, 72, 21],
       [70, 84, 71]])

In [148]:
a[:,1:]

array([[60, 55],
       [72, 21],
       [84, 71]])

In [149]:
a

array([[68, 60, 55],
       [51, 72, 21],
       [70, 84, 71]])

In [153]:
# a[[1,2],1:]

In [154]:
a

array([[68, 60, 55],
       [51, 72, 21],
       [70, 84, 71]])

In [ ]:
68,55
51,21
70,71

In [156]:
a[:,0::2]

array([[68, 55],
       [51, 21],
       [70, 71]])

In [157]:
a

array([[68, 60, 55],
       [51, 72, 21],
       [70, 84, 71]])

In [158]:
# 68,55
# 70,71

In [159]:
a[0::2,0::2]

array([[68, 55],
       [70, 71]])

In [160]:
print('Done')

Done
