In [1]:
# numpy
# pandas
# matplotlib
# seaborn

In [2]:
# ------------------------------------------
# Data Analyst
# numpy:- numerical python
# pandas:- 
# visuals:- matplotlib and seaborn,Plotly
# EDA:- Exlporatory data analysis
# Maths+ Stats
# --------------------------------------------

# BI Tools:- Power bi,tableau

# ---------------------------------------------------------

# django:- Framework:- website development
# flask:- Same
# Fast api


# ML engineers:- Sklearn,scipy
    
# Ai Engineers:- Pytorch,keras,tensorflow

In [3]:
# # Road map
# Numpy:(4)
# Pandas:(11-12)
# matplot(3)
# seaborn + Plotly(4)
# # Maths+ Stats(3-4)
# # Project(1-3)
# # Some Interview Questions(1)


# # power bi(20)

In [4]:
import numpy as np

In [8]:
# n dimensional array

a = [1,2354,4,3212,2567]

print(type(a))
print(a)

<class 'list'>
[1, 2354, 4, 3212, 2567]


In [10]:
a = np.array([1,2354,4,3212,2567])

print(a)

[   1 2354    4 3212 2567]


In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [11]:
a.ndim

1

In [12]:
# 2d array
a = [[1,2,3]]

print(a,type(a))

[[1, 2, 3]] <class 'list'>


In [13]:
arr_a = np.array(a)
arr_a

array([[1, 2, 3]])

In [14]:
arr_a.ndim

2

In [15]:
# 3d array

d3_array = [[[1,2,3,45]]]

arr_3 = np.array(d3_array)

In [16]:
arr_3

array([[[ 1,  2,  3, 45]]])

In [17]:
arr_3.ndim

3

In [19]:
# 2d

a = [[1,2,3],[3,4,5]]

d2_arr = np.array(a)

In [20]:
d2_arr

array([[1, 2, 3],
       [3, 4, 5]])

In [21]:
d2_arr.ndim

2

In [22]:
# shape

d2_arr.shape

(2, 3)

In [23]:
d2_arr

array([[1, 2, 3],
       [3, 4, 5]])

In [24]:
three_by_three_array = np.array([[1,2,3],
                                 [4,5,6],
                                 [6,7,8]])

three_by_three_array

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [25]:
print(three_by_three_array)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [26]:
three_by_three_array.shape

(3, 3)

In [27]:
five_array = np.array([[1,2],
         [2,2],
         [3,4],
         [5,6],
         [7,8]])



In [29]:
five_array.shape

(5, 2)

In [30]:
five_array.ndim

2

In [31]:
arr_33 = np.array([[[1,2,3],
          [3,4,5],
          [5,6,7]],
         
          [[1,2,3],
          [3,4,5],
          [5,6,7]],
          
          [[1,2,3],
          [0,0,0],
          [4,5,6]]])



In [32]:
print(arr_33)

[[[1 2 3]
  [3 4 5]
  [5 6 7]]

 [[1 2 3]
  [3 4 5]
  [5 6 7]]

 [[1 2 3]
  [0 0 0]
  [4 5 6]]]


In [33]:
arr_33.shape

(3, 3, 3)

In [34]:
arr_33.ndim

3

In [35]:
# (2,3,4,5)



In [36]:
arr = np.array([[[[1,2,3,4,5],
               [1,1,1,1,1],
               [2,2,2,2,2],
               [4,5,6,7,8]],
              
              [[1,2,3,4,5],
               [1,1,1,1,1],
               [2,2,2,2,2],
               [4,5,6,7,8]],
              
              [[1,2,3,4,5],
               [1,1,1,1,1],
               [2,2,2,2,2],
               [4,5,6,7,8]]],
              
              [[[1,2,3,4,5],
               [1,1,1,1,1],
               [2,2,2,2,2],
               [4,5,6,7,8]],
              
              [[1,2,3,4,5],
               [1,1,1,1,1],
               [2,2,2,2,2],
               [4,5,6,7,8]],
              
              [[1,2,3,4,5],
               [1,1,1,1,1],
               [2,2,2,2,2],
               [4,5,6,7,8]]]])

print(arr)

[[[[1 2 3 4 5]
   [1 1 1 1 1]
   [2 2 2 2 2]
   [4 5 6 7 8]]

  [[1 2 3 4 5]
   [1 1 1 1 1]
   [2 2 2 2 2]
   [4 5 6 7 8]]

  [[1 2 3 4 5]
   [1 1 1 1 1]
   [2 2 2 2 2]
   [4 5 6 7 8]]]


 [[[1 2 3 4 5]
   [1 1 1 1 1]
   [2 2 2 2 2]
   [4 5 6 7 8]]

  [[1 2 3 4 5]
   [1 1 1 1 1]
   [2 2 2 2 2]
   [4 5 6 7 8]]

  [[1 2 3 4 5]
   [1 1 1 1 1]
   [2 2 2 2 2]
   [4 5 6 7 8]]]]


In [37]:
arr.shape

(2, 3, 4, 5)

In [38]:
arr.ndim

4

In [39]:
arr.size

120

In [40]:
arr_33

array([[[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]],

       [[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]],

       [[1, 2, 3],
        [0, 0, 0],
        [4, 5, 6]]])

In [41]:
arr_33.size

27

In [42]:
# ndim
# shape
# size

In [43]:
# array:- can contain one data type at a time
# list:- can contain any data types objects


# array to list
# list to array

In [46]:
a = np.array([1,2,3])

print(a,a.dtype)

[1 2 3] int32


In [48]:
a = np.array([1,2,3,89.5])

print(a,a.dtype)

[ 1.   2.   3.  89.5] float64


In [49]:
a = np.array([1,2,3,89.5,'adil'])

print(a,a.dtype)

['1' '2' '3' '89.5' 'adil'] <U32


In [50]:
a = np.array([1,2,3,89.5,{'Name':'Ajay'}])

print(a,a.dtype)

[1 2 3 89.5 {'Name': 'Ajay'}] object


In [51]:
# we can perform mathematical op with array but not with list

In [52]:
a = [2,4,5,7,9,10]

# [4,8,10,14,18,20]

In [53]:
b = [i*2 for i in a]
b

[4, 8, 10, 14, 18, 20]

In [54]:
a = np.array([2,4,5,7,9,10])

a

array([ 2,  4,  5,  7,  9, 10])

In [55]:
a*2

array([ 4,  8, 10, 14, 18, 20])

In [56]:
[2,4,5,7,9,10]*2

[2, 4, 5, 7, 9, 10, 2, 4, 5, 7, 9, 10]

In [61]:
arr-100

array([[[[-99, -98, -97, -96, -95],
         [-99, -99, -99, -99, -99],
         [-98, -98, -98, -98, -98],
         [-96, -95, -94, -93, -92]],

        [[-99, -98, -97, -96, -95],
         [-99, -99, -99, -99, -99],
         [-98, -98, -98, -98, -98],
         [-96, -95, -94, -93, -92]],

        [[-99, -98, -97, -96, -95],
         [-99, -99, -99, -99, -99],
         [-98, -98, -98, -98, -98],
         [-96, -95, -94, -93, -92]]],


       [[[-99, -98, -97, -96, -95],
         [-99, -99, -99, -99, -99],
         [-98, -98, -98, -98, -98],
         [-96, -95, -94, -93, -92]],

        [[-99, -98, -97, -96, -95],
         [-99, -99, -99, -99, -99],
         [-98, -98, -98, -98, -98],
         [-96, -95, -94, -93, -92]],

        [[-99, -98, -97, -96, -95],
         [-99, -99, -99, -99, -99],
         [-98, -98, -98, -98, -98],
         [-96, -95, -94, -93, -92]]]])

In [63]:
arr%2

array([[[[1, 0, 1, 0, 1],
         [1, 1, 1, 1, 1],
         [0, 0, 0, 0, 0],
         [0, 1, 0, 1, 0]],

        [[1, 0, 1, 0, 1],
         [1, 1, 1, 1, 1],
         [0, 0, 0, 0, 0],
         [0, 1, 0, 1, 0]],

        [[1, 0, 1, 0, 1],
         [1, 1, 1, 1, 1],
         [0, 0, 0, 0, 0],
         [0, 1, 0, 1, 0]]],


       [[[1, 0, 1, 0, 1],
         [1, 1, 1, 1, 1],
         [0, 0, 0, 0, 0],
         [0, 1, 0, 1, 0]],

        [[1, 0, 1, 0, 1],
         [1, 1, 1, 1, 1],
         [0, 0, 0, 0, 0],
         [0, 1, 0, 1, 0]],

        [[1, 0, 1, 0, 1],
         [1, 1, 1, 1, 1],
         [0, 0, 0, 0, 0],
         [0, 1, 0, 1, 0]]]], dtype=int32)