In [1]:
# Array creation
# list to array
# 1d,2d,3d,4d...
# arr.ndim
# arr.shape
# arr.size
# arr.dtype


In [2]:
import numpy as np

In [5]:
a = np.arange(1,26)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [6]:
a.shape

(25,)

In [7]:
a.ndim

1

In [8]:
len(a)

25

In [9]:
a.dtype

dtype('int32')

In [11]:
a = np.arange(1,26,dtype = 'float')
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.])

In [12]:
a.dtype

dtype('float64')

In [13]:
a = np.arange(1,26,dtype = float)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.])

In [14]:
a = np.arange(1,26,dtype = complex)
a

array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j,
        8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j, 14.+0.j,
       15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j, 20.+0.j, 21.+0.j,
       22.+0.j, 23.+0.j, 24.+0.j, 25.+0.j])

In [15]:
# reshape

In [16]:
a = np.array([[1,2,3],
             [3,4,5],
             [5,6,7]])

a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [17]:
a.shape

(3, 3)

In [23]:
a = np.arange(1,26)
a = a.reshape(5,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [27]:
a = np.arange(34,98)
# a.size

In [28]:
8*8
16*4
4*16
32*2
2*32
1*64
64*1
4*4*4

64

In [33]:
a.reshape(32,2)
a.reshape(16,4)
a.reshape(4,16)
a.reshape(4,4,4)

array([[[34, 35, 36, 37],
        [38, 39, 40, 41],
        [42, 43, 44, 45],
        [46, 47, 48, 49]],

       [[50, 51, 52, 53],
        [54, 55, 56, 57],
        [58, 59, 60, 61],
        [62, 63, 64, 65]],

       [[66, 67, 68, 69],
        [70, 71, 72, 73],
        [74, 75, 76, 77],
        [78, 79, 80, 81]],

       [[82, 83, 84, 85],
        [86, 87, 88, 89],
        [90, 91, 92, 93],
        [94, 95, 96, 97]]])

In [38]:
np.arange(1,501).reshape(25,2,10)
np.arange(1,501).reshape(5,5,20)

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
          13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
          33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
          53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
          73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
          93,  94,  95,  96,  97,  98,  99, 100]],

       [[101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
         113, 114, 115, 116, 117, 118, 119, 120],
        [121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
         133, 134, 135, 136, 137, 138, 139, 140],
        [141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
         153, 154, 155, 156, 157, 158, 159, 160],
        [161, 162, 163, 164, 165, 166, 167, 16

In [39]:
# zeros

In [41]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [43]:
np.full((5,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [44]:
np.full((3,3),0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
np.full((5,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [49]:
np.ones((5,5))+400

array([[401., 401., 401., 401., 401.],
       [401., 401., 401., 401., 401.],
       [401., 401., 401., 401., 401.],
       [401., 401., 401., 401., 401.],
       [401., 401., 401., 401., 401.]])

In [51]:
# astype

np.ones((5,5)).dtype

dtype('float64')

In [55]:
np.ones((5,5)).astype(int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [56]:
np.ones((5,5)).astype('int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [59]:
np.ones((5,5)).astype(dict)

array([[1.0, 1.0, 1.0, 1.0, 1.0],
       [1.0, 1.0, 1.0, 1.0, 1.0],
       [1.0, 1.0, 1.0, 1.0, 1.0],
       [1.0, 1.0, 1.0, 1.0, 1.0],
       [1.0, 1.0, 1.0, 1.0, 1.0]], dtype=object)

In [61]:
np.ones((5,5)).astype(str)

array([['1.0', '1.0', '1.0', '1.0', '1.0'],
       ['1.0', '1.0', '1.0', '1.0', '1.0'],
       ['1.0', '1.0', '1.0', '1.0', '1.0'],
       ['1.0', '1.0', '1.0', '1.0', '1.0'],
       ['1.0', '1.0', '1.0', '1.0', '1.0']], dtype='<U32')

In [62]:
np.random.randint(1,100)

4

In [65]:
import random

# random.randint(1,100,25)

In [66]:
np.random.randint(1,100,25)

array([80, 19, 11, 36, 34,  8, 76, 97, 51, 35,  4, 14, 66, 82, 72, 59, 15,
       44, 66, 62, 27, 57, 57, 15, 82])

In [67]:
np.random.randint(1,100,(5,5))

array([[78, 40, 54, 44, 13],
       [24,  4,  1, 65, 14],
       [20, 90, 81, 95, 60],
       [75, 63, 66, 98, 37],
       [30, 26, 80, 91, 75]])

In [69]:
a = np.random.randint(1,100,(5,5,5,5,5))

In [70]:
5**5

3125

In [71]:
a.size

3125

In [ ]:
1,10

1,2,3,4,5,6,7,8,9,10

In [ ]:
1,10



In [72]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [74]:
1.18367347 - 1

0.18367347

In [75]:
1.36734694 - 1.18367347

0.18367347

In [76]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [77]:
np.linspace(1,10,15)

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [79]:
np.linspace(100,1000,25).reshape(5,5)

array([[ 100. ,  137.5,  175. ,  212.5,  250. ],
       [ 287.5,  325. ,  362.5,  400. ,  437.5],
       [ 475. ,  512.5,  550. ,  587.5,  625. ],
       [ 662.5,  700. ,  737.5,  775. ,  812.5],
       [ 850. ,  887.5,  925. ,  962.5, 1000. ]])

In [82]:
a = np.random.randint(1,50,(7,7))
a

array([[37, 11, 15, 45, 15,  6, 36],
       [36, 31, 26, 15, 11, 32, 43],
       [45, 40, 14,  4, 39, 44, 20],
       [ 1, 19, 45, 39,  3, 18, 30],
       [ 4,  4, 19,  8,  5,  8, 27],
       [ 1, 10, 43, 17, 19, 46, 34],
       [ 8, 45, 29, 21, 27,  7, 33]])

In [83]:
a.ndim

2

In [86]:
np.expand_dims(a,axis=0)

array([[[37, 11, 15, 45, 15,  6, 36],
        [36, 31, 26, 15, 11, 32, 43],
        [45, 40, 14,  4, 39, 44, 20],
        [ 1, 19, 45, 39,  3, 18, 30],
        [ 4,  4, 19,  8,  5,  8, 27],
        [ 1, 10, 43, 17, 19, 46, 34],
        [ 8, 45, 29, 21, 27,  7, 33]]])

In [90]:
b = np.array([a])
b

array([[[37, 11, 15, 45, 15,  6, 36],
        [36, 31, 26, 15, 11, 32, 43],
        [45, 40, 14,  4, 39, 44, 20],
        [ 1, 19, 45, 39,  3, 18, 30],
        [ 4,  4, 19,  8,  5,  8, 27],
        [ 1, 10, 43, 17, 19, 46, 34],
        [ 8, 45, 29, 21, 27,  7, 33]]])

In [94]:
b = b.flatten()

In [95]:
b.ndim

1

In [99]:
v = np.expand_dims(a,axis=0)
v

array([[[37, 11, 15, 45, 15,  6, 36],
        [36, 31, 26, 15, 11, 32, 43],
        [45, 40, 14,  4, 39, 44, 20],
        [ 1, 19, 45, 39,  3, 18, 30],
        [ 4,  4, 19,  8,  5,  8, 27],
        [ 1, 10, 43, 17, 19, 46, 34],
        [ 8, 45, 29, 21, 27,  7, 33]]])

In [100]:
v.shape

(1, 7, 7)

In [101]:
v.reshape(7,7)

array([[37, 11, 15, 45, 15,  6, 36],
       [36, 31, 26, 15, 11, 32, 43],
       [45, 40, 14,  4, 39, 44, 20],
       [ 1, 19, 45, 39,  3, 18, 30],
       [ 4,  4, 19,  8,  5,  8, 27],
       [ 1, 10, 43, 17, 19, 46, 34],
       [ 8, 45, 29, 21, 27,  7, 33]])

In [103]:
v.reshape(v.size)

array([37, 11, 15, 45, 15,  6, 36, 36, 31, 26, 15, 11, 32, 43, 45, 40, 14,
        4, 39, 44, 20,  1, 19, 45, 39,  3, 18, 30,  4,  4, 19,  8,  5,  8,
       27,  1, 10, 43, 17, 19, 46, 34,  8, 45, 29, 21, 27,  7, 33])

In [105]:
arr_6d = np.random.randint(1,101,(3,4,5,6,7,8))
arr_6d.ndim

6

In [106]:
arr_6d.flatten()

array([61, 14,  7, ..., 35, 14, 17])

In [107]:
arr_6d.size

20160

In [108]:
arr_6d.reshape(arr_6d.size)

array([61, 14,  7, ..., 35, 14, 17])