In [1]:
import numpy as np

In [9]:
np.random.seed(10)
data = np.random.randint(1,50,(3,3))
data>20

array([[False,  True, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [12]:
# Masking
data

array([[10, 37, 16],
       [ 1, 29, 26],
       [30, 49, 30]])

In [18]:
data[data>20]

array([37, 29, 26, 30, 49, 30])

In [23]:
data

array([[10, 37, 16],
       [ 1, 29, 26],
       [30, 49, 30]])

In [24]:
data[data%2!=0]

array([37,  1, 29, 49])

In [27]:
data[data%10==0]

array([10, 30, 30])

In [28]:
data

array([[10, 37, 16],
       [ 1, 29, 26],
       [30, 49, 30]])

In [31]:
five_array = np.random.randint(1,100,(5,5,5))

In [34]:
five_array[five_array>80]

array([88, 86, 83, 82, 86, 82, 97, 90, 97, 87, 93, 94, 88, 81, 92, 84, 89,
       97, 91, 91, 98, 94, 85, 85])

In [37]:
a = np.random.randint(1,50,(3,3))

In [41]:
a[(a%2==0) & (a%3==0)]

array([18, 24])

In [42]:
a

array([[45, 19, 47],
       [14,  3, 38],
       [32, 18, 24]])

In [48]:
a[(a>30)  & (a<40)  & (a%2==0)]

array([38, 32])

In [50]:
a

array([[45, 19, 47],
       [14,  3, 38],
       [32, 18, 24]])

In [51]:
a[np.where(a>10)]

array([45, 19, 47, 14, 38, 32, 18, 24])

In [52]:
a[a>10]

array([45, 19, 47, 14, 38, 32, 18, 24])

In [53]:
np.where(a>10)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1, 2], dtype=int64))

In [54]:
a

array([[45, 19, 47],
       [14,  3, 38],
       [32, 18, 24]])

In [56]:
np.where(a>10,'yes','No')

array([['yes', 'yes', 'yes'],
       ['yes', 'No', 'yes'],
       ['yes', 'yes', 'yes']], dtype='<U3')

In [61]:
a

array([[45, 19, 47],
       [14,  3, 38],
       [32, 18, 24]])

In [63]:
np.where(a==24)

(array([2], dtype=int64), array([2], dtype=int64))

In [64]:
a[2,2]

24

In [65]:
# hstack
# vstack

In [68]:
a = np.random.randint(1,20,(2,2))
b = np.random.randint(1,20,(2,2))

In [69]:
a

array([[3, 7],
       [2, 6]])

In [70]:
b

array([[ 9, 17],
       [16,  4]])

In [71]:
# [3,7,9,17]
# [2,6,16,4]

In [74]:
np.hstack([a,b])

array([[ 3,  7,  9, 17],
       [ 2,  6, 16,  4]])

In [75]:
# [3,7]
# [2,6]
# [9,17]
# [16,4]

In [78]:
c = np.vstack([a,b])
c

array([[ 3,  7],
       [ 2,  6],
       [ 9, 17],
       [16,  4]])

In [82]:
np.vsplit(c,2)[1]

array([[ 9, 17],
       [16,  4]])

In [85]:
np.vstack([a,a,a,a])

array([[3, 7],
       [2, 6],
       [3, 7],
       [2, 6],
       [3, 7],
       [2, 6],
       [3, 7],
       [2, 6]])

In [88]:
arr = np.random.randint(1,55,(3,3))
arr

array([[48,  4, 15],
       [38, 15, 45],
       [35, 52, 51]])

In [96]:
np.vsplit(arr,3)

[array([[48,  4, 15]]), array([[38, 15, 45]]), array([[35, 52, 51]])]

In [97]:
arr = np.random.randint(1,55,(4,4))
arr

array([[51, 22, 15, 53],
       [31, 18, 39, 11],
       [24,  2, 29, 11],
       [12,  2, 19, 35]])

In [100]:
np.vsplit(arr,4)

[array([[51, 22, 15, 53]]),
 array([[31, 18, 39, 11]]),
 array([[24,  2, 29, 11]]),
 array([[12,  2, 19, 35]])]

In [102]:
np.hsplit(arr,2)

[array([[51, 22],
        [31, 18],
        [24,  2],
        [12,  2]]),
 array([[15, 53],
        [39, 11],
        [29, 11],
        [19, 35]])]

In [111]:
np.random.seed(10)
a = np.random.randint(1,55,20)
np.array(list(reversed(np.sort(a))))

array([52, 50, 50, 49, 43, 41, 37, 37, 37, 30, 30, 29, 26, 17, 16, 10, 10,
        9,  1,  1])

In [112]:
a

array([10, 37, 16,  1, 50, 29, 26, 30, 49, 30, 50,  9, 10,  1, 43, 41, 37,
       52, 17, 37])

In [113]:
np.clip(a,10,30)

array([10, 30, 16, 10, 30, 29, 26, 30, 30, 30, 30, 10, 10, 10, 30, 30, 30,
       30, 17, 30])

In [115]:
b = np.copy(a)

In [116]:
b

array([10, 37, 16,  1, 50, 29, 26, 30, 49, 30, 50,  9, 10,  1, 43, 41, 37,
       52, 17, 37])

In [117]:
a = np.random.randint(1,20,(5,5))
a

array([[16, 12, 12,  2,  9],
       [ 5, 15, 18, 14,  6],
       [14, 14, 13,  2,  5],
       [19, 14, 12, 11, 10],
       [16, 19, 17,  8, 12]])

In [126]:
a

array([[ True, False, False, False, False],
       [False,  True,  True,  True, False],
       [ True,  True,  True, False, False],
       [ True,  True, False, False, False],
       [ True,  True,  True, False, False]])